<a href="https://colab.research.google.com/github/Jit687/10-Essential-Excel-Formulas/blob/main/ReshapehStackArray.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [1]:
import numpy as np

# Climate data for the Kanto region (temperature, rainfall, humidity)
climate_data = np.array([73, 67, 43])

# Assigned weights based on historical data (impact factors)
weights = np.array([0.3, 0.2, 0.5])

# Calculate yield using the dot product formula
predicted_yield = np.dot(climate_data, weights)

print(f"The expected apple yield is: {predicted_yield} tons per hectare.")


The expected apple yield is: 56.8 tons per hectare.


In [2]:
import numpy as np

# Climate data for the kanto region, temp, rainfall, humidity
climate_data = np.array([[93, 88, 73]])

# Assigned weights based on historical data
weights = np.array([0.1, 0.1, 0.3])

# Calculate yield using the dot product formula
predicted_yield = np.dot(climate_data, weights)
print(f"The expected apple yield is: {predicted_yield[0]} tons per hectare.")



The expected apple yield is: 40.0 tons per hectare.


In [3]:
import numpy as np

# Climate data from two different regions
climate_data1 = np.array([[73, 67, 43]])
climate_data2 = np.array([[91, 88, 64]])

# join the arrays horizontally
merged_data = np.concatenate((climate_data1, climate_data2))

print("Joined Climate Data", merged_data)

Joined Climate Data [[73 67 43]
 [91 88 64]]


In [4]:
climate_data = np.array([[73, 67, 43]])
weights = np.array([0.3, 0.2, 0.5])

# Calculate yield using the dot product formula
predicted_yield = np.dot(climate_data, weights)
print(f"The expected apple yield is: {predicted_yield[0]} tons per hectare.")

The expected apple yield is: 56.8 tons per hectare.


In [5]:
import numpy as np

climate_data1 = np.array([[73, 67, 43]]) # Region 1
climate_data2 = np.array([[91, 88, 64]]) # Region 2
# Horizontally joining (axis=1)
horizontal = np.concatenate((climate_data1, climate_data2), axis=1)
# Vertically joining (axis=0)
vertical = np.concatenate((climate_data1, climate_data2), axis=0)

print("Joined Climate Data Horizontal):", horizontal)
print("Joined Climate Data Vertical):", vertical)


Joined Climate Data Horizontal): [[73 67 43 91 88 64]]
Joined Climate Data Vertical): [[73 67 43]
 [91 88 64]]


In [6]:
import numpy as np

climate_dataA = np.array([[63, 49, 52]]) # Region 1
climate_dataB = np.array([[71, 66, 59]]) # Region 2
# Horizantally joining (axis=1)
horizontal = np.hstack((climate_dataA, climate_dataB))
# Vertically joining (axis=0)
vertical = np.vstack((climate_dataA, climate_dataB))
print("hstack Climate Data (Horizontal):", horizontal)
print("vstack Climate Data (Vertical):", vertical)

hstack Climate Data (Horizontal): [[63 49 52 71 66 59]]
vstack Climate Data (Vertical): [[63 49 52]
 [71 66 59]]


In [7]:
import numpy as np

arr = np.array([1, 2, 3, 4, 5, 6, 7, 8, 9, 10, 11, 12])
reshaped_arr = arr.reshape(4, 3)

print("Reshaped Array:\n", reshaped_arr)

Reshaped Array:
 [[ 1  2  3]
 [ 4  5  6]
 [ 7  8  9]
 [10 11 12]]


In [13]:
import numpy as np

matrix = np.array([[7, 8, 9],
                   [4, 5, 6],
                   [7, 8, 9]])
flattened_matrix = matrix.flatten()

print("Flattened Matrix:\n", flattened_matrix)

# Transpose the matrix
transposed_matrix = matrix.T

print("Transposed Matrix:\n", transposed_matrix)

Flattened Matrix:
 [7 8 9 4 5 6 7 8 9]
Transposed Matrix:
 [[7 4 7]
 [8 5 8]
 [9 6 9]]
